"""
Portal Client - Unified communication layer for Droidrun Portal app.

This module provides automatic TCP/Content Provider fallback for Portal communication.
"""

import asyncio
import base64
import io
import json
import logging
import re
from typing import Any, Dict, List, Optional

import httpx
from async_adbutils import AdbDevice

logger = logging.getLogger("droidrun")

PORTAL_REMOTE_PORT = 8080  # Port on device where Portal HTTP server runs

# Granular timeout policy for the persistent session.
# Separating connect/read/write/pool prevents slow devices from causing
# cascading stalls when socket reuse is delayed by network jitter.
_SESSION_TIMEOUT = httpx.Timeout(
    connect=5.0,   # TCP handshake (only on first request per connection)
    read=15.0,     # Portal response time (state_full can be slow on busy devices)
    write=10.0,    # Request upload (keyboard input payloads are small)
    pool=5.0,      # Wait for a connection from the pool
)

# Tighter timeout for lightweight probe calls (ping, version)
_PROBE_TIMEOUT = httpx.Timeout(connect=5.0, read=5.0, write=5.0, pool=5.0)


class PortalClient:
    """
    Unified client for Droidrun Portal communication.

    Automatically handles TCP vs Content Provider fallback with the following strategy:
    - On init, checks for existing port forward and reuses it
    - If no forward exists, creates new one
    - Fetches auth token and tests connection before enabling TCP
    - Maintains a persistent httpx.AsyncClient for all TCP requests
    - All methods auto-select TCP or content provider based on availability
    - Port forwards persist until device disconnect (no explicit cleanup needed)

    Key features:
    - Reuses existing port forwards (no cleanup needed)
    - Persistent HTTP session eliminates per-call TCP handshake overhead
    - Bearer token auth for Portal HTTP server
    - Graceful degradation to content provider on any TCP failure
    - Self-healing: 401/403 triggers token re-fetch and session rebuild

    Note: TCP mode is significantly faster but requires ADB port forwarding.
    Content provider mode works without port forwarding but has higher latency.
    """

    def __init__(self, device: AdbDevice, prefer_tcp: bool = False):
        """
        Initialize Portal client.

        Args:
            device: ADB device instance
            prefer_tcp: Whether to prefer TCP communication (will fallback to
                        content provider if unavailable)

        Note:
            Call `await client.connect()` after initialization to establish
            connection. Call `await client.disconnect()` when done to release
            the persistent HTTP session.
        """
        self.device = device
        self.prefer_tcp = prefer_tcp
        self.tcp_available = False
        self.tcp_base_url = None
        self.local_tcp_port = None
        self._auth_token: Optional[str] = None
        # Persistent session — None until TCP successfully connects.
        # Invariant: _session is not None IFF tcp_available is True.
        self._session: Optional[httpx.AsyncClient] = None
        self._connected = False

    async def connect(self) -> None:
        """
        Establish connection to Portal.

        If prefer_tcp=True, attempts to set up TCP mode with auth.
        Always falls back to content provider on any failure.
        """
        if self._connected:
            return

        if self.prefer_tcp:
            await self._try_enable_tcp()

        self._connected = True

    async def disconnect(self) -> None:
        """
        Release the persistent HTTP session and reset connection state.

        Safe to call multiple times (idempotent). After disconnect(),
        connect() can be called again to re-establish.
        """
        if self._session is not None:
            try:
                await self._session.aclose()
            except Exception:
                pass
            self._session = None

        # Enforce invariant: no session means TCP not available
        self.tcp_available = False
        self._connected = False

    async def _ensure_connected(self) -> None:
        """Check if connected, raise error if not."""
        if not self._connected:
            await self.connect()

    async def _fetch_auth_token(self) -> Optional[str]:
        """
        Fetch the auth token from the Portal via the content provider.

        The Portal HTTP server requires a Bearer token for all requests.
        The token is generated by the Portal app and exposed via the content
        provider, which is only accessible over ADB (secure channel).

        Returns:
            The auth token string, or None if unavailable.
        """
        try:
            output = await self.device.shell(
                "content query --uri content://com.droidrun.portal/auth_token"
            )
            data = self._parse_content_provider_output(output)
            if data is None:
                logger.debug("Auth token: unparseable content provider output")
                return None

            # Extract token — handle various response shapes
            token = None
            if isinstance(data, dict):
                token = (
                    data.get("token")
                    or data.get("auth_token")
                    or data.get("result")
                    or data.get("data")
                )
                # Unwrap nested dict: {"status": "success", "result": {"token": "..."}}
                if isinstance(token, dict):
                    token = token.get("token") or token.get("auth_token")
            elif isinstance(data, str):
                token = data

            if token and isinstance(token, str):
                logger.debug("Auth token retrieved from Portal")
                return token

            logger.debug(f"Auth token: unexpected response format: {data}")
            return None

        except Exception as e:
            logger.debug(f"Failed to fetch auth token: {e}")
            return None

    @property
    def _tcp_headers(self) -> Dict[str, str]:
        """HTTP headers for all TCP requests, including auth when available."""
        headers: Dict[str, str] = {}
        if self._auth_token:
            headers["Authorization"] = f"Bearer {self._auth_token}"
        return headers

    def _build_session(self) -> httpx.AsyncClient:
        """
        Build a new persistent AsyncClient with current auth headers.

        Uses granular httpx.Timeout to prevent socket-reuse stalls on slow
        or remote devices. Called only after TCP is confirmed working.
        """
        return httpx.AsyncClient(
            headers=self._tcp_headers,
            timeout=_SESSION_TIMEOUT,
        )

    async def _replace_session(self) -> None:
        """
        Close any existing session and build a fresh one with current token.

        Used when the token rotates (server restart, 401 recovery) so the
        persistent session's default Authorization header stays current.
        Safe to call whether or not a session currently exists.
        """
        if self._session is not None:
            try:
                await self._session.aclose()
            except Exception:
                pass
        self._session = self._build_session()

    async def _degrade_to_cp(self, reason: str) -> None:
        """
        Gracefully downgrade from TCP to content provider.

        Called on unrecoverable TCP failures (connection errors, fatal status
        codes). Closes the session cleanly, resets state, and logs once so
        operators can diagnose without being spammed.
        """
        if self._session is not None:
            try:
                await self._session.aclose()
            except Exception:
                pass
            self._session = None
        if self.tcp_available:
            logger.warning(
                f"Portal TCP degraded → falling back to content provider. Reason: {reason}"
            )
        self.tcp_available = False

    async def _try_enable_tcp(self) -> None:
        """
        Try to enable TCP communication. Fails silently and falls back to
        content provider.

        Strategy:
        1. Fetch auth token via content provider (secure ADB channel)
        2. Check if port forward already exists → reuse
        3. If not, create new forward
        4. Test connection via /version (authenticated endpoint, not /ping)
        5. Build persistent session ONLY on confirmed success
        6. Set tcp_available flag
        """
        # Clean up any session left over from a previous connect() call.
        # Handles reconnect scenario: disconnect() then connect() again.
        if self._session is not None:
            try:
                await self._session.aclose()
            except Exception:
                pass
            self._session = None

        try:
            # Step 1: Fetch auth token before any HTTP calls
            self._auth_token = await self._fetch_auth_token()
            if not self._auth_token:
                logger.debug(
                    "No auth token available — Portal may not require auth, "
                    "proceeding without it"
                )

            # Step 2: Check for existing forward
            local_port = await self._find_existing_forward()

            # Step 3: If no forward exists, create one
            if local_port is None:
                logger.debug(
                    f"No existing forward found, creating new forward for port {PORTAL_REMOTE_PORT}"
                )
                local_port = await self.device.forward_port(PORTAL_REMOTE_PORT)
                logger.debug(
                    f"Created forward: localhost:{local_port} -> device:{PORTAL_REMOTE_PORT}"
                )
            else:
                logger.debug(
                    f"Reusing existing forward: localhost:{local_port} -> device:{PORTAL_REMOTE_PORT}"
                )

            self.local_tcp_port = local_port
            self.tcp_base_url = f"http://localhost:{local_port}"

            # Step 4: Test connection using /version (requires auth).
            # /ping does NOT require auth — a 200 from /ping only proves
            # reachability, not that the token is valid. Using /version
            # confirms both reachability and auth are working before we
            # commit to TCP mode and build a persistent session.
            if await self._test_connection():
                # Step 5: Build persistent session ONLY after confirmed success.
                # Enforces invariant: _session is not None ↔ tcp_available.
                self._session = self._build_session()
                self.tcp_available = True
                logger.debug(f"✓ TCP mode enabled: {self.tcp_base_url}")
            else:
                # Step 4b: Try enabling the HTTP server via content provider
                logger.debug(
                    "TCP auth probe failed, trying to enable Portal HTTP server..."
                )
                await self.device.shell(
                    "content insert --uri content://com.droidrun.portal/toggle_socket_server --bind enabled:b:true"
                )
                await asyncio.sleep(1)

                # Re-fetch token — server restart may generate a new one
                new_token = await self._fetch_auth_token()
                if new_token:
                    self._auth_token = new_token

                if await self._test_connection():
                    # Build session only after confirmed success on retry
                    self._session = self._build_session()
                    self.tcp_available = True
                    logger.debug(
                        f"✓ TCP mode enabled after starting server: {self.tcp_base_url}"
                    )
                else:
                    logger.warning("TCP unavailable, using content provider fallback")
                    self.tcp_available = False

        except Exception as e:
            logger.warning(f"TCP unavailable ({e}), using content provider fallback")
            # Ensure no zombie session on any exception path
            if self._session is not None:
                try:
                    await self._session.aclose()
                except Exception:
                    pass
                self._session = None
            self.tcp_available = False

    async def _find_existing_forward(self) -> Optional[int]:
        """
        Check if a forward already exists for the Portal remote port.

        Returns:
            Local port number if forward exists, None otherwise
        """
        try:
            forwards = []
            async for forward in self.device.forward_list():
                forwards.append(forward)
            for forward in forwards:
                if (
                    forward.serial == self.device.serial
                    and forward.remote == f"tcp:{PORTAL_REMOTE_PORT}"
                ):
                    # Extract local port from "tcp:12345"
                    match = re.search(r"tcp:(\d+)", forward.local)
                    if match:
                        local_port = int(match.group(1))
                        logger.debug(
                            f"Found existing forward: localhost:{local_port} -> {PORTAL_REMOTE_PORT}"
                        )
                        return local_port
        except Exception as e:
            logger.debug(f"Failed to check existing forwards: {e}")

        return None

    async def _tcp_request(
        self,
        method: str,
        url: str,
        extra_headers: Optional[Dict[str, str]] = None,
        **kwargs,
    ) -> Optional[httpx.Response]:
        """
        Make an authenticated TCP request via the persistent session.

        Single choke-point for all TCP HTTP traffic. Handles:
        - Auth header injection
        - 401/403 token refresh and session rebuild
        - Connection-level failures → graceful CP downgrade

        Args:
            method: HTTP method string ("GET", "POST", ...).
            url: Full URL to request.
            extra_headers: Additional headers merged on top of auth headers.
            **kwargs: Passed through to session.request().

        Returns:
            httpx.Response on success, or None if TCP is no longer available.
            Callers must check for None and fall back to content provider.
        """
        # Soft guard: if TCP has already been disabled (by a prior failure or
        # explicit disconnect), return None so callers fall back to CP.
        # We use a warning log rather than a hard crash because agent loops
        # must stay resilient through transient state transitions.
        if not self.tcp_available or self._session is None:
            logger.debug(
                "_tcp_request called but TCP transport is not active — falling back"
            )
            return None

        headers = {**self._tcp_headers, **(extra_headers or {})}

        try:
            response = await self._session.request(method, url, headers=headers, **kwargs)

            if response.status_code in (401, 403):
                logger.debug(
                    f"TCP auth rejected ({response.status_code}), re-fetching token..."
                )
                new_token = await self._fetch_auth_token()
                if new_token:
                    self._auth_token = new_token
                    # Rebuild session so Authorization header is current
                    await self._replace_session()
                    headers = {**self._tcp_headers, **(extra_headers or {})}
                    response = await self._session.request(
                        method, url, headers=headers, **kwargs
                    )

            return response

        except (httpx.ConnectError, httpx.RemoteProtocolError, httpx.NetworkError) as e:
            # Connection-level failure: the device has gone away, ADB forward
            # was torn down, or the Portal process died. Downgrade to CP so
            # the agent can continue rather than crashing.
            await self._degrade_to_cp(str(e))
            return None

        except Exception as e:
            # Unexpected error — log and return None for CP fallback.
            # Do not degrade permanently on unknown errors (could be transient).
            logger.debug(f"TCP request error ({method} {url}): {e}")
            return None

    async def _test_connection(self) -> bool:
        """
        Test if TCP connection to Portal is working (authenticated).

        Uses /version which requires a valid Bearer token. This ensures
        that tcp_available=True means both reachability AND auth are
        confirmed — unlike /ping which returns 200 without any token.

        Intentionally uses a temporary httpx.AsyncClient (not self._session)
        so that doctor.py and CLI diagnostics can call this without affecting
        the persistent session lifecycle.
        """
        try:
            async with httpx.AsyncClient() as client:
                response = await client.get(
                    f"{self.tcp_base_url}/version",
                    headers=self._tcp_headers,
                    timeout=_PROBE_TIMEOUT,
                )
                return response.status_code == 200
        except Exception as e:
            logger.debug(f"TCP connection test failed: {e}")
            return False

    def _parse_content_provider_output(
        self, raw_output: str
    ) -> Optional[Dict[str, Any]]:
        """
        Parse the raw ADB content provider output and extract JSON data.

        Args:
            raw_output: Raw output from ADB content query command

        Returns:
            Parsed JSON data or None if parsing failed
        """
        lines = raw_output.strip().split("\n")

        # Try line-by-line parsing
        for line in lines:
            line = line.strip()

            # Look for "result=" pattern (common content provider format)
            if "result=" in line:
                result_start = line.find("result=") + 7
                json_str = line[result_start:]
                try:
                    json_data = json.loads(json_str)
                    if isinstance(json_data, dict):
                        inner_key = (
                            "result"
                            if "result" in json_data
                            else "data" if "data" in json_data else None
                        )
                        if inner_key:
                            inner_value = json_data[inner_key]
                            if isinstance(inner_value, str):
                                try:
                                    return json.loads(inner_value)
                                except json.JSONDecodeError:
                                    return inner_value
                            return inner_value
                    return json_data
                except json.JSONDecodeError:
                    continue

            # Fallback: try lines starting with JSON
            elif line.startswith("{") or line.startswith("["):
                try:
                    return json.loads(line)
                except json.JSONDecodeError:
                    continue

        # Last resort: try parsing entire output
        try:
            return json.loads(raw_output.strip())
        except json.JSONDecodeError:
            return None

    async def get_state(self) -> Dict[str, Any]:
        """
        Get device state (accessibility tree + phone state).
        Auto-selects TCP or content provider.

        Returns:
            Dictionary containing 'a11y_tree' and 'phone_state' keys
        """
        await self._ensure_connected()
        if self.tcp_available:
            return await self._get_state_tcp()
        return await self._get_state_content_provider()

    async def _get_state_tcp(self) -> Dict[str, Any]:
        """Get state via TCP."""
        response = await self._tcp_request(
            "GET", f"{self.tcp_base_url}/state_full", timeout=15
        )
        if response is not None and response.status_code == 200:
            data = response.json()
            if isinstance(data, dict):
                inner_key = (
                    "result"
                    if "result" in data
                    else "data" if "data" in data else None
                )
                if inner_key:
                    inner_value = data[inner_key]
                    if isinstance(inner_value, str):
                        try:
                            return json.loads(inner_value)
                        except json.JSONDecodeError:
                            pass
                    elif isinstance(inner_value, dict):
                        return inner_value
            return data

        logger.debug("TCP get_state failed, using content provider fallback")
        return await self._get_state_content_provider()

    async def _get_state_content_provider(self) -> Dict[str, Any]:
        """Get state via content provider (fallback)."""
        try:
            output = await self.device.shell(
                "content query --uri content://com.droidrun.portal/state_full"
            )
            state_data = self._parse_content_provider_output(output)

            if state_data is None:
                return {
                    "error": "Parse Error",
                    "message": "Failed to parse state data from ContentProvider",
                }

            if isinstance(state_data, dict):
                inner_key = (
                    "result"
                    if "result" in state_data
                    else "data" if "data" in state_data else None
                )
                if inner_key:
                    inner_value = state_data[inner_key]
                    if isinstance(inner_value, str):
                        try:
                            return json.loads(inner_value)
                        except json.JSONDecodeError:
                            return {
                                "error": "Parse Error",
                                "message": "Failed to parse nested JSON data",
                            }
                    elif isinstance(inner_value, dict):
                        return inner_value

            return state_data

        except Exception as e:
            return {"error": "ContentProvider Error", "message": str(e)}

    async def input_text(self, text: str, clear: bool = False) -> bool:
        """
        Input text via keyboard.
        Auto-selects TCP or content provider.

        Args:
            text: Text to input
            clear: Whether to clear existing text first

        Returns:
            True if successful, False otherwise
        """
        await self._ensure_connected()
        if self.tcp_available:
            return await self._input_text_tcp(text, clear)
        return await self._input_text_content_provider(text, clear)

    async def _input_text_tcp(self, text: str, clear: bool) -> bool:
        """Input text via TCP."""
        encoded = base64.b64encode(text.encode()).decode()
        payload = {"base64_text": encoded, "clear": clear}
        response = await self._tcp_request(
            "POST",
            f"{self.tcp_base_url}/keyboard/input",
            extra_headers={"Content-Type": "application/json"},
            json=payload,
            timeout=10,
        )
        if response is not None and response.status_code == 200:
            logger.debug("TCP input_text successful")
            return True

        logger.debug("TCP input_text failed, using content provider fallback")
        return await self._input_text_content_provider(text, clear)

    async def _input_text_content_provider(self, text: str, clear: bool) -> bool:
        """Input text via content provider (fallback)."""
        try:
            encoded = base64.b64encode(text.encode()).decode()
            clear_str = "true" if clear else "false"
            cmd = (
                f'content insert --uri "content://com.droidrun.portal/keyboard/input" '
                f'--bind base64_text:s:"{encoded}" '
                f"--bind clear:b:{clear_str}"
            )
            await self.device.shell(cmd)
            logger.debug("Content provider input_text successful")
            return True
        except Exception as e:
            logger.error(f"Content provider input_text error: {e}")
            return False

    async def take_screenshot(self, hide_overlay: bool = True) -> bytes:
        """
        Take screenshot of device.
        Auto-selects TCP or ADB screencap.

        Args:
            hide_overlay: Whether to hide Portal overlay during screenshot

        Returns:
            Screenshot image bytes (PNG format)
        """
        await self._ensure_connected()
        if self.tcp_available:
            return await self._take_screenshot_tcp(hide_overlay)
        return await self._take_screenshot_adb()

    async def _take_screenshot_tcp(self, hide_overlay: bool) -> bytes:
        """Take screenshot via TCP."""
        url = f"{self.tcp_base_url}/screenshot"
        if not hide_overlay:
            url += "?hideOverlay=false"

        response = await self._tcp_request("GET", url, timeout=15.0)
        if response is not None and response.status_code == 200:
            data = response.json()
            if data.get("status") == "success":
                inner_key = (
                    "result"
                    if "result" in data
                    else "data" if "data" in data else None
                )
                if inner_key:
                    logger.debug("Screenshot taken via TCP")
                    return base64.b64decode(data[inner_key])

        logger.debug("TCP screenshot failed, using ADB fallback")
        return await self._take_screenshot_adb()

    async def _take_screenshot_adb(self) -> bytes:
        """Take screenshot via ADB screencap (fallback)."""
        data = await self.device.screenshot_bytes()
        logger.debug("Screenshot taken via ADB")
        return data

    async def get_apps(self, include_system: bool = True) -> List[Dict[str, str]]:
        """
        Get installed apps with package name and label.

        Note: Currently only supports content provider (no TCP endpoint exists yet)

        Args:
            include_system: Whether to include system apps

        Returns:
            List of dicts with 'package' and 'label' keys
        """
        await self._ensure_connected()
        try:
            logger.debug("Getting apps via content provider")

            output = await self.device.shell(
                "content query --uri content://com.droidrun.portal/packages"
            )
            packages_data = self._parse_content_provider_output(output)

            if not packages_data:
                logger.warning("No packages data found in content provider response")
                return []

            packages_list = None
            if isinstance(packages_data, list):
                packages_list = packages_data
            elif isinstance(packages_data, dict):
                if "packages" in packages_data:
                    packages_list = packages_data["packages"]
                else:
                    inner_key = (
                        "result"
                        if "result" in packages_data
                        else "data" if "data" in packages_data else None
                    )
                    if inner_key:
                        inner_value = packages_data[inner_key]
                        if isinstance(inner_value, list):
                            packages_list = inner_value
                        elif (
                            isinstance(inner_value, dict) and "packages" in inner_value
                        ):
                            packages_list = inner_value["packages"]

            if not packages_list:
                logger.warning("Could not extract packages list from response")
                return []

            apps = []
            for package_info in packages_list:
                if not include_system and package_info.get("isSystemApp", False):
                    continue
                apps.append(
                    {
                        "package": package_info.get("packageName", ""),
                        "label": package_info.get("label", ""),
                    }
                )

            logger.debug(f"Found {len(apps)} apps")
            return apps

        except Exception as e:
            logger.error(f"Error getting apps: {e}")
            raise ValueError(f"Error getting apps: {e}") from e

    async def get_version(self) -> str:
        """Get Portal app version."""
        await self._ensure_connected()
        if self.tcp_available:
            response = await self._tcp_request(
                "GET", f"{self.tcp_base_url}/version", timeout=5.0
            )
            if response is not None and response.status_code == 200:
                data = response.json()
                inner_key = (
                    "result"
                    if "result" in data
                    else "data" if "data" in data else None
                )
                if inner_key:
                    return data[inner_key]
                return data.get("status", "unknown")

        # Fallback to content provider
        try:
            output = await self.device.shell(
                "content query --uri content://com.droidrun.portal/version"
            )
            result = self._parse_content_provider_output(output)
            if result:
                inner_key = (
                    "result"
                    if "result" in result
                    else "data" if "data" in result else None
                )
                if inner_key:
                    return result[inner_key]
        except Exception:
            pass

        return "unknown"

    async def ping(self) -> Dict[str, Any]:
        """
        Test Portal connection and verify state availability.

        Returns:
            Dictionary with status and connection details
        """
        await self._ensure_connected()
        if self.tcp_available:
            response = await self._tcp_request(
                "GET", f"{self.tcp_base_url}/ping", timeout=5.0
            )
            if response is not None and response.status_code == 200:
                try:
                    tcp_response = response.json() if response.content else {}
                    result = {
                        "status": "success",
                        "method": "tcp",
                        "url": self.tcp_base_url,
                        "response": tcp_response,
                    }
                except json.JSONDecodeError:
                    result = {
                        "status": "success",
                        "method": "tcp",
                        "url": self.tcp_base_url,
                        "response": response.text if response else "",
                    }
            else:
                return {
                    "status": "error",
                    "method": "tcp",
                    "message": (
                        f"HTTP {response.status_code}: {response.text}"
                        if response is not None
                        else "TCP not available"
                    ),
                }
        else:
            # Test content provider
            try:
                output = await self.device.shell(
                    "content query --uri content://com.droidrun.portal/state"
                )
                if "Row: 0 result=" in output:
                    result = {"status": "success", "method": "content_provider"}
                else:
                    return {
                        "status": "error",
                        "method": "content_provider",
                        "message": "Invalid response",
                    }
            except Exception as e:
                return {
                    "status": "error",
                    "method": "content_provider",
                    "message": str(e),
                }

        # Verify state has the required keys
        try:
            state = await self.get_state()
            required = ("a11y_tree", "phone_state", "device_context")
            missing = [k for k in required if k not in state]
            if missing:
                return {
                    "status": "error",
                    "method": result.get("method", "unknown"),
                    "message": f"incompatible portal — missing {', '.join(missing)}",
                }
        except Exception as e:
            return {
                "status": "error",
                "method": result.get("method", "unknown"),
                "message": f"state check failed: {e}",
            }

        return result
